local env = env
GLOBAL.setfenv(1, GLOBAL)



env.AddPrefabPostInit("moonpig",function(inst)
    if not TheWorld.ismastersim then
        return
    end

    if inst.components.lootdropper~=nil then
        inst.components.lootdropper:SetLoot({ "meat", "pigskin" })
        inst.components.lootdropper.numrandomloot = 1
        inst.components.lootdropper:AddRandomLoot("opalpreciousgem", 0.2)
        inst.components.lootdropper:AddRandomLoot("ruins_bat", 0.5)
        inst.components.lootdropper:AddRandomLoot("nightsword", 1)
        inst.components.lootdropper:AddRandomLoot("glasscutter", 1)
        inst.components.lootdropper:AddRandomLoot("ruinshat", 1)
        inst.components.lootdropper:AddRandomLoot("armorruins", 1)
        inst.components.lootdropper:AddRandomLoot("slurtlehat", 1)
        inst.components.lootdropper:AddRandomLoot("hivehat", 0.5)
        inst.components.lootdropper:AddRandomLoot("skeletonhat", 1)
        inst.components.lootdropper:AddRandomLoot("armor_sanity", 1)
        inst.components.lootdropper:AddRandomLoot("armorsnurtleshell", 1)
        inst.components.lootdropper:AddRandomLoot("armordragonfly", 1)
        inst.components.lootdropper:AddRandomLoot("armorskeleton", 0.5)
        inst.components.lootdropper:AddRandomLoot("krampus_sack", 0.2)
        inst.components.lootdropper:AddRandomLoot("orangestaff", 1)
        inst.components.lootdropper:AddRandomLoot("yellowstaff", 1)
        inst.components.lootdropper:AddRandomLoot("greenstaff", 1)
        inst.components.lootdropper:AddRandomLoot("opalstaff", 0.5)
        inst.components.lootdropper:AddRandomLoot("orangeamulet", 0.5)
        inst.components.lootdropper:AddRandomLoot("yellowamulet", 0.5)
        inst.components.lootdropper:AddRandomLoot("greenamulet", 0.5)
        inst.components.lootdropper:AddRandomLoot("dragon_scales", 1)
        inst.components.lootdropper:AddRandomLoot("shroom_skin", 1)
        inst.components.lootdropper:AddRandomLoot("multitool_axe_pickaxe", 1)
        inst.components.lootdropper:AddRandomLoot("rock_avocado_fruit_sprout", 1)
        inst.components.lootdropper:AddRandomLoot("eyeturret_item", 1)
        inst.components.lootdropper:AddRandomLoot("nightmare_timepiece", 1)
        inst.components.lootdropper:AddRandomLoot("panflute", 1)

        inst.components.lootdropper:AddRandomLoot("nightmarefuel", 3)
        inst.components.lootdropper:AddRandomLoot("livinglog", 3)
        inst.components.lootdropper:AddRandomLoot("umbrella", 3)
        inst.components.lootdropper:AddRandomLoot("tentaclespike", 2.5)
        inst.components.lootdropper:AddRandomLoot("surfnturf", 2.5)
        inst.components.lootdropper:AddRandomLoot("lobsterbisque", 2.5)
        inst.components.lootdropper:AddRandomLoot("voltgoatjelly", 2)
        inst.components.lootdropper:AddRandomLoot("meatysalad", 2.5)
        inst.components.lootdropper:AddRandomLoot("dragonpie", 2.5)
        inst.components.lootdropper:AddRandomLoot("powcake", 3)
        inst.components.lootdropper:AddRandomLoot("waffles", 2.5)
        inst.components.lootdropper:AddRandomLoot("butter", 2.5)
        inst.components.lootdropper:AddRandomLoot("deserthat", 2.5)
        inst.components.lootdropper:AddRandomLoot("walrushat", 2.5)
        inst.components.lootdropper:AddRandomLoot("eyebrellahat", 2.5)
        inst.components.lootdropper:AddRandomLoot("trunkvest_summer", 2.5)
        inst.components.lootdropper:AddRandomLoot("trunkvest_winter", 2.5)
        inst.components.lootdropper:AddRandomLoot("beargervest", 2)
        inst.components.lootdropper:AddRandomLoot("reflectivevest", 3)
        inst.components.lootdropper:AddRandomLoot("raincoat", 2.5)
        inst.components.lootdropper:AddRandomLoot("malbatross_beak", 2)
        inst.components.lootdropper:AddRandomLoot("lantern", 3)
        inst.components.lootdropper:AddRandomLoot("featherfan", 2)
        inst.components.lootdropper:AddRandomLoot("thulecite", 3)
        inst.components.lootdropper:AddRandomLoot("turf_dragonfly", 3)
        inst.components.lootdropper:AddRandomLoot("greengem", 2.5)
        inst.components.lootdropper:AddRandomLoot("orangegem", 2.5)
        inst.components.lootdropper:AddRandomLoot("yellowgem", 2.5)
        inst.components.lootdropper:AddRandomLoot("moonglass", 3)
        inst.components.lootdropper:AddRandomLoot("chesspiece_pipe_marble", 3)
        inst.components.lootdropper:AddRandomLoot("premiumwateringcan", 2)
        inst.components.lootdropper:AddRandomLoot("cane", 2.5)
        inst.components.lootdropper:AddRandomLoot("staff_tornado", 2)
        inst.components.lootdropper:AddRandomLoot("bundlewrap", 3)
        inst.components.lootdropper:AddRandomLoot("steelwool", 3)
        inst.components.lootdropper:AddRandomLoot("honeycomb", 3)
        inst.components.lootdropper:AddRandomLoot("spidereggsack", 3)
        inst.components.lootdropper:AddRandomLoot("heatrock", 3)
        inst.components.lootdropper:AddRandomLoot("bugnet", 3)
        inst.components.lootdropper:AddRandomLoot("birdtrap", 3)
        inst.components.lootdropper:AddRandomLoot("sewing_kit", 3)
        inst.components.lootdropper:AddRandomLoot("bushhat", 2.5)
        inst.components.lootdropper:AddRandomLoot("icehat", 3)
        inst.components.lootdropper:AddRandomLoot("rainhat", 3)
        inst.components.lootdropper:AddRandomLoot("deerclops_eyeball", 2.5)
        inst.components.lootdropper:AddRandomLoot("tallbirdegg", 3)
        inst.components.lootdropper:AddRandomLoot("trap_teeth", 3)
        inst.components.lootdropper:AddRandomLoot("trinket_13", 3)
        inst.components.lootdropper:AddRandomLoot("trinket_4", 3)
        inst.components.lootdropper:AddRandomLoot("trunk_summer", 3)
        inst.components.lootdropper:AddRandomLoot("trunk_winter", 2.5)

        inst.components.lootdropper:AddRandomLoot("meat", 5)
        inst.components.lootdropper:AddRandomLoot("meatballs", 4)
        inst.components.lootdropper:AddRandomLoot("perogies", 4)
        inst.components.lootdropper:AddRandomLoot("baconeggs", 4)
        inst.components.lootdropper:AddRandomLoot("frogglebunwich", 4)
        inst.components.lootdropper:AddRandomLoot("goldnugget", 5)
        inst.components.lootdropper:AddRandomLoot("rocks", 5)
        inst.components.lootdropper:AddRandomLoot("silk", 4)
        inst.components.lootdropper:AddRandomLoot("spidergland", 4)
        inst.components.lootdropper:AddRandomLoot("stinger", 5)
        inst.components.lootdropper:AddRandomLoot("poop", 5)
        inst.components.lootdropper:AddRandomLoot("log", 5)
        inst.components.lootdropper:AddRandomLoot("boards", 5)
        inst.components.lootdropper:AddRandomLoot("cutgrass", 5)
        inst.components.lootdropper:AddRandomLoot("rope", 5)
        inst.components.lootdropper:AddRandomLoot("twigs", 5)
        inst.components.lootdropper:AddRandomLoot("cutstone", 5)
        inst.components.lootdropper:AddRandomLoot("thulecite_pieces", 5)
        inst.components.lootdropper:AddRandomLoot("featherpencil", 4)
        inst.components.lootdropper:AddRandomLoot("torch", 4)
        inst.components.lootdropper:AddRandomLoot("green_cap", 5)
        inst.components.lootdropper:AddRandomLoot("red_cap", 5)
        inst.components.lootdropper:AddRandomLoot("blue_cap", 5)
        inst.components.lootdropper:AddRandomLoot("seeds", 5)
        inst.components.lootdropper:AddRandomLoot("carrot_seeds", 5)
        inst.components.lootdropper:AddRandomLoot("gears", 4)
        inst.components.lootdropper:AddRandomLoot("houndstooth", 5)
        inst.components.lootdropper:AddRandomLoot("spear", 5)
        inst.components.lootdropper:AddRandomLoot("hammer", 5)
        inst.components.lootdropper:AddRandomLoot("pinecone", 5)
        inst.components.lootdropper:AddRandomLoot("acorn", 5)
        inst.components.lootdropper:AddRandomLoot("twiggy_nut", 5)
        inst.components.lootdropper:AddRandomLoot("pickaxe", 5)
        inst.components.lootdropper:AddRandomLoot("goldenpickaxe", 4)
        inst.components.lootdropper:AddRandomLoot("axe", 5)
        inst.components.lootdropper:AddRandomLoot("goldenaxe", 4)
        inst.components.lootdropper:AddRandomLoot("shovel", 5)
        inst.components.lootdropper:AddRandomLoot("goldenshovel", 4)
        inst.components.lootdropper:AddRandomLoot("blowdart_pipe", 5)
        inst.components.lootdropper:AddRandomLoot("beefalowool", 5)
        inst.components.lootdropper:AddRandomLoot("beardhair", 5)
        inst.components.lootdropper:AddRandomLoot("saltrock", 4)
        inst.components.lootdropper:AddRandomLoot("feather_crow", 5)
        inst.components.lootdropper:AddRandomLoot("grass_umbrella", 5)
        inst.components.lootdropper:AddRandomLoot("trap", 5)
        inst.components.lootdropper:AddRandomLoot("boatpatch", 5)
        inst.components.lootdropper:AddRandomLoot("flowerhat", 5)
        inst.components.lootdropper:AddRandomLoot("kelphat", 5)
        inst.components.lootdropper:AddRandomLoot("strawhat", 5)
        inst.components.lootdropper:AddRandomLoot("purplegem", 5)
        inst.components.lootdropper:AddRandomLoot("bluegem", 5)
        inst.components.lootdropper:AddRandomLoot("redgem", 5)
        inst.components.lootdropper:AddRandomLoot("marble", 5)
        inst.components.lootdropper:AddRandomLoot("kabobs", 5)
        inst.components.lootdropper:AddRandomLoot("minifan", 5)
        inst.components.lootdropper:AddRandomLoot("cutreeds", 5)
        inst.components.lootdropper:AddRandomLoot("papyrus", 5)
        inst.components.lootdropper:AddRandomLoot("smallmeat", 5)
        inst.components.lootdropper:AddRandomLoot("fishingrod", 5)
        inst.components.lootdropper:AddRandomLoot("honey ", 5)
        inst.components.lootdropper:AddRandomLoot("healingsalve", 5)
        inst.components.lootdropper:AddRandomLoot("manrabbit_tail", 5)
        inst.components.lootdropper:AddRandomLoot("pondfish", 5)
        inst.components.lootdropper:AddRandomLoot("lightbulb", 5)
        inst.components.lootdropper:AddRandomLoot("plantmeat", 5)
        inst.components.lootdropper:AddRandomLoot("flint", 5)
    end
end)




env.AddPrefabPostInit("pigman",function(inst)
    if not TheWorld.ismastersim then
        return
    end

    if inst.components.lootdropper~=nil then
        inst.components.lootdropper:SetLoot({})
        inst.components.lootdropper.numrandomloot = 1

        inst.components.lootdropper:AddRandomLoot("ruins_bat",1.5)
        inst.components.lootdropper:AddRandomLoot("nightsword",1.5)
        inst.components.lootdropper:AddRandomLoot("glasscutter",1.5)
        inst.components.lootdropper:AddRandomLoot("ruinshat",1)
        inst.components.lootdropper:AddRandomLoot("armorruins",1)
        inst.components.lootdropper:AddRandomLoot("slurtlehat",1)
        inst.components.lootdropper:AddRandomLoot("armor_sanity",1.5)
        inst.components.lootdropper:AddRandomLoot("armorsnurtleshell",1.5)
        inst.components.lootdropper:AddRandomLoot("orangestaff",0.5)
        inst.components.lootdropper:AddRandomLoot("orangeamulet",0.5)
        inst.components.lootdropper:AddRandomLoot("yellowamulet",0.5)
        inst.components.lootdropper:AddRandomLoot("greenamulet",0.5)
        inst.components.lootdropper:AddRandomLoot("dragon_scales",1)
        inst.components.lootdropper:AddRandomLoot("shroom_skin",0.5)
        inst.components.lootdropper:AddRandomLoot("multitool_axe_pickaxe",1)
        inst.components.lootdropper:AddRandomLoot("rock_avocado_fruit_sprout",1)
        inst.components.lootdropper:AddRandomLoot("panflute",1)
        inst.components.lootdropper:AddRandomLoot("beargervest",0.5)
        inst.components.lootdropper:AddRandomLoot("surfnturf",1)
        inst.components.lootdropper:AddRandomLoot("lobsterbisque",1)
        inst.components.lootdropper:AddRandomLoot("voltgoatjelly",0.5)
        inst.components.lootdropper:AddRandomLoot("deserthat",1.5)
        inst.components.lootdropper:AddRandomLoot("walrushat",1)
        inst.components.lootdropper:AddRandomLoot("eyebrellahat",1)
        inst.components.lootdropper:AddRandomLoot("malbatross_beak",0.5)
        inst.components.lootdropper:AddRandomLoot("deerclops_eyeball",1)
        inst.components.lootdropper:AddRandomLoot("premiumwateringcan",0.5)
        inst.components.lootdropper:AddRandomLoot("cane",1.5)
        inst.components.lootdropper:AddRandomLoot("staff_tornado",1)
        inst.components.lootdropper:AddRandomLoot("nightmare_timepiece",1)
        inst.components.lootdropper:AddRandomLoot("bundlewrap",2)

        inst.components.lootdropper:AddRandomLoot("nightmarefuel",3)
        inst.components.lootdropper:AddRandomLoot("livinglog",3)
        inst.components.lootdropper:AddRandomLoot("meatysalad",3)
        inst.components.lootdropper:AddRandomLoot("dragonpie",3)
        inst.components.lootdropper:AddRandomLoot("powcake",3)
        inst.components.lootdropper:AddRandomLoot("butter",2)
        inst.components.lootdropper:AddRandomLoot("deserthat",3)
        inst.components.lootdropper:AddRandomLoot("trunkvest_summer",3)
        inst.components.lootdropper:AddRandomLoot("trunkvest_winter",2)
        inst.components.lootdropper:AddRandomLoot("reflectivevest",3)
        inst.components.lootdropper:AddRandomLoot("raincoat",3)
        inst.components.lootdropper:AddRandomLoot("thulecite",3)
        inst.components.lootdropper:AddRandomLoot("turf_dragonfly",2.5)
        inst.components.lootdropper:AddRandomLoot("greengem",2)
        inst.components.lootdropper:AddRandomLoot("orangegem",2)
        inst.components.lootdropper:AddRandomLoot("yellowgem",2)

        inst.components.lootdropper:AddRandomLoot("",240)

        inst.components.lootdropper:AddRandomLoot("moonglass",3)
        inst.components.lootdropper:AddRandomLoot("chesspiece_pipe_marble",3)
        inst.components.lootdropper:AddRandomLoot("steelwool",2.5)
        inst.components.lootdropper:AddRandomLoot("honeycomb",3)
        inst.components.lootdropper:AddRandomLoot("spidereggsack",3)
        inst.components.lootdropper:AddRandomLoot("heatrock",3)
        inst.components.lootdropper:AddRandomLoot("bugnet",3)
        inst.components.lootdropper:AddRandomLoot("birdtrap",3)
        inst.components.lootdropper:AddRandomLoot("sewing_kit",3)
        inst.components.lootdropper:AddRandomLoot("bushhat",2.5)
        inst.components.lootdropper:AddRandomLoot("icehat",3)
        inst.components.lootdropper:AddRandomLoot("rainhat",3)
        inst.components.lootdropper:AddRandomLoot("tallbirdegg",3)
        inst.components.lootdropper:AddRandomLoot("trap_teeth",3)
        inst.components.lootdropper:AddRandomLoot("trinket_7",3)
        inst.components.lootdropper:AddRandomLoot("trunk_summer",2.5)
        inst.components.lootdropper:AddRandomLoot("trunk_winter",2.5)
        inst.components.lootdropper:AddRandomLoot("meatballs",3)
        inst.components.lootdropper:AddRandomLoot("perogies",3)
        inst.components.lootdropper:AddRandomLoot("baconeggs",3)
        inst.components.lootdropper:AddRandomLoot("goldenpickaxe",3)
        inst.components.lootdropper:AddRandomLoot("goldenaxe",3)
        inst.components.lootdropper:AddRandomLoot("goldenshovel",3)
        inst.components.lootdropper:AddRandomLoot("saltrock",3)
        inst.components.lootdropper:AddRandomLoot("healingsalve",3)

        inst.components.lootdropper:AddRandomLoot("meat", 5)
        inst.components.lootdropper:AddRandomLoot("pigskin", 5)
        inst.components.lootdropper:AddRandomLoot("frogglebunwich", 5)
        inst.components.lootdropper:AddRandomLoot("goldnugget", 5)
        inst.components.lootdropper:AddRandomLoot("rocks", 5)
        inst.components.lootdropper:AddRandomLoot("spidergland", 5)
        inst.components.lootdropper:AddRandomLoot("stinger", 5)
        inst.components.lootdropper:AddRandomLoot("poop", 5)
        inst.components.lootdropper:AddRandomLoot("log", 5)
        inst.components.lootdropper:AddRandomLoot("cutgrass", 5)
        inst.components.lootdropper:AddRandomLoot("twigs", 5)
        inst.components.lootdropper:AddRandomLoot("thulecite_pieces", 5)
        inst.components.lootdropper:AddRandomLoot("featherpencil", 5)
        inst.components.lootdropper:AddRandomLoot("torch", 5)
        inst.components.lootdropper:AddRandomLoot("green_cap", 5)
        inst.components.lootdropper:AddRandomLoot("red_cap", 5)
        inst.components.lootdropper:AddRandomLoot("blue_cap", 5)
        inst.components.lootdropper:AddRandomLoot("seeds", 5)
        inst.components.lootdropper:AddRandomLoot("houndstooth", 5)
        inst.components.lootdropper:AddRandomLoot("spear", 5)
        inst.components.lootdropper:AddRandomLoot("hammer", 5)
        inst.components.lootdropper:AddRandomLoot("pinecone", 5)
        inst.components.lootdropper:AddRandomLoot("acorn", 5)
        inst.components.lootdropper:AddRandomLoot("twiggy_nut", 5)
        inst.components.lootdropper:AddRandomLoot("pickaxe", 5)
        inst.components.lootdropper:AddRandomLoot("axe", 5)
        inst.components.lootdropper:AddRandomLoot("shovel", 5)
        inst.components.lootdropper:AddRandomLoot("blowdart_pipe", 5)
        inst.components.lootdropper:AddRandomLoot("beefalowool",5)
        inst.components.lootdropper:AddRandomLoot("beardhair", 5)
        inst.components.lootdropper:AddRandomLoot("saltrock", 5)
        inst.components.lootdropper:AddRandomLoot("feather_crow", 5)
        inst.components.lootdropper:AddRandomLoot("grass_umbrella", 5)
        inst.components.lootdropper:AddRandomLoot("trap", 5)
        inst.components.lootdropper:AddRandomLoot("boatpatch", 5)
        inst.components.lootdropper:AddRandomLoot("flowerhat", 5)
        inst.components.lootdropper:AddRandomLoot("kelphat", 5)
        inst.components.lootdropper:AddRandomLoot("strawhat", 5)
        inst.components.lootdropper:AddRandomLoot("purplegem", 5)
        inst.components.lootdropper:AddRandomLoot("bluegem", 5)
        inst.components.lootdropper:AddRandomLoot("redgem", 5)
        inst.components.lootdropper:AddRandomLoot("marble", 5)
        inst.components.lootdropper:AddRandomLoot("kabobs", 5)
        inst.components.lootdropper:AddRandomLoot("minifan", 5)
        inst.components.lootdropper:AddRandomLoot("cutreeds", 5)
        inst.components.lootdropper:AddRandomLoot("smallmeat", 5)
        inst.components.lootdropper:AddRandomLoot("fishingrod", 5)
        inst.components.lootdropper:AddRandomLoot("honey ", 5)
        inst.components.lootdropper:AddRandomLoot("healingsalve", 5)
        inst.components.lootdropper:AddRandomLoot("pondfish", 5)
        inst.components.lootdropper:AddRandomLoot("lightbulb", 5)
        inst.components.lootdropper:AddRandomLoot("plantmeat", 5)
        inst.components.lootdropper:AddRandomLoot("flint", 5)

    end
end)
