local env = env
GLOBAL.setfenv(1,GLOBAL)


env.AddPrefabPostInit("rabbit",function(inst)
    if not TheWorld.ismastersim then
        return
    end
    
    inst.components.lootdropper.numrandomloot = 1
    inst.components.lootdropper:AddRandomLoot("meat", 5)
    inst.components.lootdropper:AddRandomLoot("goldnugget", 5)
    inst.components.lootdropper:AddRandomLoot("rocks", 5)
    inst.components.lootdropper:AddRandomLoot("silk", 5)
    inst.components.lootdropper:AddRandomLoot("spidergland", 5)
    inst.components.lootdropper:AddRandomLoot("stinger", 5)
    inst.components.lootdropper:AddRandomLoot("poop", 5)
    inst.components.lootdropper:AddRandomLoot("log", 5)
    inst.components.lootdropper:AddRandomLoot("cutgrass", 5)
    inst.components.lootdropper:AddRandomLoot("twigs", 5)
    inst.components.lootdropper:AddRandomLoot("thulecite_pieces", 5)
    inst.components.lootdropper:AddRandomLoot("featherpencil", 4)
    inst.components.lootdropper:AddRandomLoot("torch", 4)
    inst.components.lootdropper:AddRandomLoot("green_cap", 5)
    inst.components.lootdropper:AddRandomLoot("red_cap", 5)
    inst.components.lootdropper:AddRandomLoot("blue_cap", 5)
    inst.components.lootdropper:AddRandomLoot("seeds", 5)
    inst.components.lootdropper:AddRandomLoot("houndstooth", 5)
    inst.components.lootdropper:AddRandomLoot("spear", 5)
    inst.components.lootdropper:AddRandomLoot("pinecone", 5)
    inst.components.lootdropper:AddRandomLoot("acorn", 5)
    inst.components.lootdropper:AddRandomLoot("twiggy_nut", 5)

    inst.components.lootdropper:AddRandomLoot("", 160)

    inst.components.lootdropper:AddRandomLoot("shovel", 5)
    inst.components.lootdropper:AddRandomLoot("axe", 5)
    inst.components.lootdropper:AddRandomLoot("pickaxe", 5)
    inst.components.lootdropper:AddRandomLoot("blowdart_pipe", 5)
    inst.components.lootdropper:AddRandomLoot("beefalowool", 5)
    inst.components.lootdropper:AddRandomLoot("beardhair", 5)
    inst.components.lootdropper:AddRandomLoot("saltrock", 5)
    inst.components.lootdropper:AddRandomLoot("feather_crow", 5)
    inst.components.lootdropper:AddRandomLoot("grass_umbrella", 5)
    inst.components.lootdropper:AddRandomLoot("trap", 5)
    inst.components.lootdropper:AddRandomLoot("boatpatch", 5)
    inst.components.lootdropper:AddRandomLoot("purplegem", 3)
    inst.components.lootdropper:AddRandomLoot("redgem", 3)
    inst.components.lootdropper:AddRandomLoot("bluegem", 3)
    inst.components.lootdropper:AddRandomLoot("marble", 5)
    inst.components.lootdropper:AddRandomLoot("kabobs", 5)
    inst.components.lootdropper:AddRandomLoot("minifan", 5)
    inst.components.lootdropper:AddRandomLoot("cutreeds", 5)
    inst.components.lootdropper:AddRandomLoot("smallmeat", 5)
    inst.components.lootdropper:AddRandomLoot("fishingrod", 5)
    inst.components.lootdropper:AddRandomLoot("honey ", 5)
    inst.components.lootdropper:AddRandomLoot("pondfish", 5)

    inst.components.lootdropper:AddRandomLoot("nightmarefuel", 1)
    inst.components.lootdropper:AddRandomLoot("livinglog", 1)
    inst.components.lootdropper:AddRandomLoot("tentaclespike", 1)
    inst.components.lootdropper:AddRandomLoot("surfnturf", 1)
    inst.components.lootdropper:AddRandomLoot("powcake", 2)
    inst.components.lootdropper:AddRandomLoot("waffles", 1)
    inst.components.lootdropper:AddRandomLoot("butter", 0.5)
    inst.components.lootdropper:AddRandomLoot("raincoat", 1)
    inst.components.lootdropper:AddRandomLoot("lantern", 1)
    inst.components.lootdropper:AddRandomLoot("featherfan", 0.2)
    inst.components.lootdropper:AddRandomLoot("thulecite", 0.5)
    inst.components.lootdropper:AddRandomLoot("greengem", 0.1)
    inst.components.lootdropper:AddRandomLoot("orangegem", 0.1)
    inst.components.lootdropper:AddRandomLoot("yellowgem", 0.1)
    inst.components.lootdropper:AddRandomLoot("staff_tornado", 0.1)
    inst.components.lootdropper:AddRandomLoot("bundlewrap", 0.5)
    inst.components.lootdropper:AddRandomLoot("steelwool", 1)
    inst.components.lootdropper:AddRandomLoot("honeycomb", 1)
    inst.components.lootdropper:AddRandomLoot("spidereggsack", 1)
    inst.components.lootdropper:AddRandomLoot("heatrock", 1)
    inst.components.lootdropper:AddRandomLoot("sewing_kit", 0.5)
    inst.components.lootdropper:AddRandomLoot("rainhat", 1)
    inst.components.lootdropper:AddRandomLoot("deerclops_eyeball", 1)
    inst.components.lootdropper:AddRandomLoot("tallbirdegg", 0.5)
    inst.components.lootdropper:AddRandomLoot("trinket_6", 0.5)
    inst.components.lootdropper:AddRandomLoot("goldenpickaxe", 1)
    inst.components.lootdropper:AddRandomLoot("goldenaxe", 1)
    inst.components.lootdropper:AddRandomLoot("goldenshovel", 1)
    inst.components.lootdropper:AddRandomLoot("boards", 1)
    inst.components.lootdropper:AddRandomLoot("rope", 1)
    inst.components.lootdropper:AddRandomLoot("cutstone", 1)
    inst.components.lootdropper:AddRandomLoot("hammer", 1)
    inst.components.lootdropper:AddRandomLoot("healingsalve", 0.5)
    inst.components.lootdropper:AddRandomLoot("panflute", 0.5)
end)






