local env = env
GLOBAL.setfenv(1, GLOBAL)


local SpiderNames ={"spider","spider_warrior"}

for i, SpiderName in ipairs(SpiderNames) do
    env.AddPrefabPostInit(SpiderName, function(inst)
        if not TheWorld.ismastersim then
            return
        end
        
        if inst.components.lootdropper ~= nil then
            inst.components.lootdropper:AddChanceLoot("monstermeat", 0.6)
            inst.components.lootdropper:AddChanceLoot("silk", 0.4)
            inst.components.lootdropper:AddChanceLoot("spidergland", 0.4)
    
            inst.components.lootdropper.randomloot = {}
            inst.components.lootdropper.numrandomloot = 1
            inst.components.lootdropper:AddRandomLoot("goldnugget", 4)
            inst.components.lootdropper:AddRandomLoot("rocks", 4)
            inst.components.lootdropper:AddRandomLoot("silk", 4)
            inst.components.lootdropper:AddRandomLoot("spidergland", 4)
            inst.components.lootdropper:AddRandomLoot("stinger", 4)
            inst.components.lootdropper:AddRandomLoot("poop", 4)
            inst.components.lootdropper:AddRandomLoot("log", 4)
            inst.components.lootdropper:AddRandomLoot("boards", 4)
            inst.components.lootdropper:AddRandomLoot("cutgrass", 4)
            inst.components.lootdropper:AddRandomLoot("rope", 4)
            inst.components.lootdropper:AddRandomLoot("twigs", 4)
            inst.components.lootdropper:AddRandomLoot("cutstone", 4)
            inst.components.lootdropper:AddRandomLoot("thulecite_pieces", 4)
            inst.components.lootdropper:AddRandomLoot("green_cap", 4)
            inst.components.lootdropper:AddRandomLoot("blue_cap", 4)
            inst.components.lootdropper:AddRandomLoot("red_cap", 4)
            inst.components.lootdropper:AddRandomLoot("seeds", 4)
            inst.components.lootdropper:AddRandomLoot("gears", 4)
            inst.components.lootdropper:AddRandomLoot("houndstooth", 4)
            inst.components.lootdropper:AddRandomLoot("pinecone", 4)
            inst.components.lootdropper:AddRandomLoot("acorn", 4)
            inst.components.lootdropper:AddRandomLoot("twiggy_nut", 4)
            inst.components.lootdropper:AddRandomLoot("shovel", 4)
            inst.components.lootdropper:AddRandomLoot("axe", 4)
            inst.components.lootdropper:AddRandomLoot("pickaxe", 4)
            inst.components.lootdropper:AddRandomLoot("blowdart_pipe", 4)
            inst.components.lootdropper:AddRandomLoot("beefalowool", 4)
            inst.components.lootdropper:AddRandomLoot("beardhair", 4)
            inst.components.lootdropper:AddRandomLoot("saltrock", 4)
            inst.components.lootdropper:AddRandomLoot("feather_crow", 4)
            inst.components.lootdropper:AddRandomLoot("boatpatch", 4)
            inst.components.lootdropper:AddRandomLoot("purplegem", 2)
            inst.components.lootdropper:AddRandomLoot("bluegem", 2)
            inst.components.lootdropper:AddRandomLoot("redgem", 2)
            inst.components.lootdropper:AddRandomLoot("marble", 4)
            inst.components.lootdropper:AddRandomLoot("kabobs", 4)
            inst.components.lootdropper:AddRandomLoot("minifan", 4)
            inst.components.lootdropper:AddRandomLoot("cutreeds", 4)
            inst.components.lootdropper:AddRandomLoot("papyrus", 4)
            inst.components.lootdropper:AddRandomLoot("smallmeat", 4)
            inst.components.lootdropper:AddRandomLoot("honey", 4)
            inst.components.lootdropper:AddRandomLoot("healingsalve", 4)
            inst.components.lootdropper:AddRandomLoot("manrabbit_tail", 4)
            inst.components.lootdropper:AddRandomLoot("pondfish", 4)
    
            inst.components.lootdropper:AddRandomLoot("nightmarefuel", 1.5)
            inst.components.lootdropper:AddRandomLoot("livinglog", 1.5)
            inst.components.lootdropper:AddRandomLoot("tentaclespike", 1.5)
            inst.components.lootdropper:AddRandomLoot("surfnturf", 1)
            inst.components.lootdropper:AddRandomLoot("lobsterbisque", 1)
            inst.components.lootdropper:AddRandomLoot("meatysalad", 1)
            inst.components.lootdropper:AddRandomLoot("dragonpie", 1)
            inst.components.lootdropper:AddRandomLoot("powcake", 1)
            inst.components.lootdropper:AddRandomLoot("waffles", 1)
            inst.components.lootdropper:AddRandomLoot("lantern", 1.5)
            inst.components.lootdropper:AddRandomLoot("featherfan", 2)
            inst.components.lootdropper:AddRandomLoot("thulecite", 1.5)
            inst.components.lootdropper:AddRandomLoot("turf_dragonfly", 1.5)
            inst.components.lootdropper:AddRandomLoot("greengem", 0.5)
            inst.components.lootdropper:AddRandomLoot("orangegem", 0.5)
            inst.components.lootdropper:AddRandomLoot("yellowgem", 0.5)
            inst.components.lootdropper:AddRandomLoot("chesspiece_moon_moonglass", 1.5)
            inst.components.lootdropper:AddRandomLoot("cane", 0.5)
            inst.components.lootdropper:AddRandomLoot("staff_tornado", 0.5)
            inst.components.lootdropper:AddRandomLoot("bundlewrap", 0.5)
            inst.components.lootdropper:AddRandomLoot("honeycomb", 1)
            inst.components.lootdropper:AddRandomLoot("spidereggsack", 1)
            inst.components.lootdropper:AddRandomLoot("sewing_kit", 1)
            inst.components.lootdropper:AddRandomLoot("trap_teeth", 1)
            inst.components.lootdropper:AddRandomLoot("trinket_12", 2)
    
    
            inst.components.lootdropper:AddRandomLoot("opalpreciousgem", 0.05)
            inst.components.lootdropper:AddRandomLoot("ruins_bat", 0.1)
            inst.components.lootdropper:AddRandomLoot("nightsword", 0.3)
            inst.components.lootdropper:AddRandomLoot("glasscutter", 0.2)
            inst.components.lootdropper:AddRandomLoot("ruinshat", 0.3)
            inst.components.lootdropper:AddRandomLoot("armorruins", 0.3)
            inst.components.lootdropper:AddRandomLoot("slurtlehat", 0.1)
            inst.components.lootdropper:AddRandomLoot("armor_sanity", 0.4)
            inst.components.lootdropper:AddRandomLoot("armorsnurtleshell", 0.1)
            inst.components.lootdropper:AddRandomLoot("orangestaff", 0.05)
            inst.components.lootdropper:AddRandomLoot("greenstaff", 0.05)
            inst.components.lootdropper:AddRandomLoot("orangeamulet", 0.05)
            inst.components.lootdropper:AddRandomLoot("yellowamulet", 0.05)
            inst.components.lootdropper:AddRandomLoot("multitool_axe_pickaxe", 0.2)
            inst.components.lootdropper:AddRandomLoot("rock_avocado_fruit_sprout", 0.5)
            inst.components.lootdropper:AddRandomLoot("nightmare_timepiece", 0.5)
            inst.components.lootdropper:AddRandomLoot("steelwool", 0.5)
            inst.components.lootdropper:AddRandomLoot("sewing_kit", 0.3)
        end
    end)
end


